### ISSUE TITLE
failing test "expect(received).toBe(expected) // Object.is equality"

### ISSUE THREAD

**Issue by jastuccio** [debugg-xyz/pretty-formatting#1]
```
// index.js
const fs = require('fs');

function showFiles() {
  // let files;
  fs.readdir('/home/faraaz/', {}, (error, files) => {
    console.log(files);
  });
}

function isFile(entry) {
  try {
    fs.access(entry);
  } catch (error) {
    console.log(error);
  }
}

showFiles();
```

from my terminal
`
$ npm test

> pretty-formatting@1.0.0 test /Users/joe/Tutorials/www.debugg.me/pretty-formatting
> jest

 FAIL  ./index.test.js
  ✕ check if file is properly formatted (41ms)

  ● check if file is properly formatted

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

       6 |       parser: 'babel',
       7 |     })
    >  8 |   ).toBe(true);
         |     ^
       9 | });
      10 | 

      at Object.<anonymous> (index.test.js:8:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.162s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
`

this has something to do with index.test.js looking for prettier?

**Comment by faraazahmad** [comment]
Hi @jastuccio , Thanks for opening the issue! The problem statement says that the user needs to format the file properly, which is why index.js has bad formatting. 

I use prettier in the test file to check this, the test is supposed to fail here, because index.js has bad formatting.

**Comment by faraazahmad** [comment]
I used prettier in VSCode and then the test was passing but now its failing when I manually format it. I'm looking into this

**Comment by faraazahmad** [comment]
So the prettier CLI says there's no formatting problem in the code but the API doesn't

```bash
faraaz@pop-os:~/pretty-formatting$ yarn test
yarn run v1.21.1
$ jest
 FAIL  ./index.test.js
  ✕ check if file is properly formatted (31ms)

  ● check if file is properly formatted

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      2 | 
      3 | test('check if file is properly formatted', () => {
    > 4 |     expect(prettier.check('index.js', { parser: 'babel' })).toBe(true);
        |                                                             ^
      5 | })

      at Object.<anonymous> (index.test.js:4:61)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.013s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

faraaz@pop-os:~/pretty-formatting$ ./node_modules/prettier/bin-prettier.js -c index.js 
Checking formatting...
All matched files use Prettier code style!
```
